[project]
name = "vr-automation"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "langgraph>=0.0.20",
    "langchain>=0.1.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
    "python-dotenv>=1.0.0",
    "pydantic>=2.0.0",
    "holidays>=0.35",
    "pytest>=7.4.0",
]